# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user = User.create([
    {
    id: 1,
    email: "nouser@readit.com",
    password: "123456",
    password_confirmation: "123456",
    firstName: "No",
    lastName: "User",
    birthDay: 01,
    birthMonth: 01,
    birthYear: 2022,
    },
    {
    id: 2,
    email: "none@nomail.com",
    password: "123456",
    password_confirmation: "123456",
    firstName: "PJ",
    lastName: "Olender",
    birthDay: 07,
    birthMonth: 15,
    birthYear: 1945,
    },
    {
    id: 3,
    email: "erica@readit.com",
    password: "123456",
    password_confirmation: "123456",
    firstName: "Erica",
    lastName: "Stepanek",
    birthDay: 03,
    birthMonth: 10,
    birthYear: 1993,
    }
])

books = Book.create([
    {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    description: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry. After a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry. Though Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.",
    genre: "Fiction",
    totalPage: 309,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474154022l/3._SY475_.jpg",
    user_id: 1,
    },
    {
    title: "Harry Potter and the Chamber of Secrets",
    author: " J.K. Rowling",
    description: "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike. And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possible be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!",
    genre: "Fiction",
    totalPage: 341,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474169725l/15881._SY475_.jpg",
    user_id: 1,
    },
    {
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    description: "For use in schools and libraries only. During his third year at Hogwarts School for Witchcraft and Wizardry, Harry Potter must confront the devious and dangerous wizard responsible for his parents' deaths.",
    genre: "Fiction, Magic",
    totalPage: 435,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630547330l/5._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    description: "Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.",
    genre: "Fiction, Magic",
    totalPage: 734,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554006152l/6.jpg",
    user_id: 1,  
    },
    {
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    description: "There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror? Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop. As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.",
    genre: "Fiction, Magic",
    totalPage: 870,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
    user_id: 1,  
    },
    {
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    description: "The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet . . . As in all wars, life goes on. The Weasley twins expand their business. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are never straightforward, through Harry receives some extraordinary help from the mysterious Half-Blood Prince. So it's the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complete story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability.",
    genre: "Fiction, Magic, Adventure",
    totalPage: 652,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1587697303l/1._SX318_.jpg",
    user_id: 1,  
    },
    {
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    description: "It's no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it's up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry's Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death.",
    genre: "Fiction, Magic, Adventure",
    totalPage: 759,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474171184l/136251._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    description: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry. After a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry. Though Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.",
    genre: "Fiction",
    totalPage: 309,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474154022l/3._SY475_.jpg",
    user_id: 2,
    },
    {
    title: "Harry Potter and the Chamber of Secrets",
    author: " J.K. Rowling",
    description: "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike. And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possible be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!",
    genre: "Fiction",
    totalPage: 341,
    readPage: 250,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474169725l/15881._SY475_.jpg",
    user_id: 2,
    },
    {
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    description: "For use in schools and libraries only. During his third year at Hogwarts School for Witchcraft and Wizardry, Harry Potter must confront the devious and dangerous wizard responsible for his parents' deaths.",
    genre: "Fiction, Magic",
    totalPage: 435,
    readPage: 50,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630547330l/5._SY475_.jpg",
    user_id: 2,  
    },
    {
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    description: "Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.",
    genre: "Fiction, Magic",
    totalPage: 734,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554006152l/6.jpg",
    user_id: 2,  
    },
    {
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    description: "There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror? Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop. As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.",
    genre: "Fiction, Magic",
    totalPage: 870,
    readPage: 865,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
    user_id: 2,  
    },
    {
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    description: "The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet . . . As in all wars, life goes on. The Weasley twins expand their business. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are never straightforward, through Harry receives some extraordinary help from the mysterious Half-Blood Prince. So it's the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complete story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability.",
    genre: "Fiction, Magic, Adventure",
    totalPage: 652,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1587697303l/1._SX318_.jpg",
    user_id: 2,  
    },
    {
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    description: "It's no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it's up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry's Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death.",
    genre: "Fiction, Magic, Adventure",
    totalPage: 759,
    readPage: 547,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474171184l/136251._SY475_.jpg",
    user_id: 2,  
    },
    {
    title: "Rot & Ruin",
    author: "Jonathan Maberry",
    description: "In the zombie-infested, post-apocalyptic America where Benny Imura lives, every teenager must find a job by the time they turn fifteen or get their rations cut in half. Benny doesn't want to apprentice as a zombie hunter with his boring older brother Tom, but he has no choice. He expects a tedious job whacking zoms for cash, but what he gets is a vocation that will teach him what it means to be human.",
    genre: "Horror, Zombies, Science-Fiction",
    totalPage: 458,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1264898635l/7157310.jpg",
    user_id: 2,  
    },
    {
    title: "The Curious Incident of the Dog in the Night-Time",
    author: "Mark Haddon",
    description: "Christopher John Francis Boone knows all the countries of the world and their capitals and every prime number up to 7,057. He relates well to animals but has no understanding of human emotions. He cannot stand to be touched. And he detests the color yellow. This improbable story of Christopher’s quest to investigate the suspicious death of a neighborhood dog makes for one of the most captivating, unusual, and widely heralded novels in recent years.",
    genre: "Fiction, Mystery, Young Adult, Classics",
    totalPage: 226,
    readPage: 25,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1479863624l/1618._SY475_.jpg",
    user_id: 2,  
    },
    {
    title: "Hook, Line, and Sinker",
    author: "Tessa Bailey",
    description: "King crab fisherman Fox Thornton has a reputation as a sexy, carefree flirt. Everyone knows he's a guaranteed good time--in bed and out--and that's exactly how he prefers it. Until he meets Hannah Bellinger. She's immune to his charm and looks, but she seems to enjoy his... personality? And wants to be friends? Bizarre. But he likes her too much to risk a fling, so platonic pals it is. Now, Hannah's in town for work, crashing in Fox's spare bedroom. She knows he's a notorious ladies' man, but they're definitely just friends. In fact, she's nursing a hopeless crush on a colleague and Fox is just the person to help with her lackluster love life. Armed with a few tips from Westport's resident Casanova, Hannah sets out to catch her coworker's eye... yet the more time she spends with Fox, the more she wants him instead. As the line between friendship and flirtation begins to blur, Hannah can't deny she loves everything about Fox, but she refuses to be another notch on his bedpost. Living with his best friend should have been easy. Except now she's walking around in a towel, sleeping right across the hall, and Fox is fantasizing about waking up next to her for the rest of his life and... and... man overboard! He's fallen for her, hook, line, and sinker. Helping her flirt with another guy is pure torture, but maybe if Fox can tackle his inner demons and show Hannah he's all in, she'll choose him instead?",
    genre: "Romance, Contemporary, Adult",
    totalPage: 385,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1382938138l/12650149.jpg",
    user_id: 2,  
    },
    {
    title: "User Stories Applied: For Agile Software Development",
    author: "Mike Cohn",
    description: "A requirements process that saves time, eliminates rework, and leads directly to better software",
    isInReadingList: false,
    isInPersonalLibraryList: true,
    isRead: true,
    genre: "Computers and Software",
    totalPage: 258,
    readPage: 258,
    image: "https://images-na.ssl-images-amazon.com/images/I/513FxsKjReL._SX376_BO1,204,203,200_.jpg",
    user_id: 3,  
    },
    {
    title: "BoneShaker",
    author: "Cherie Priest",
    description: "In the early days of the Civil War, rumors of gold in the frozen Klondike brought hordes of newcomers to the Pacific Northwest. Anxious to compete, Russian prospectors commissioned inventor Leviticus Blue to create a great machine that could mine through Alaska’s ice. Thus was Dr. Blue’s Incredible Bone-Shaking Drill Engine born. But on its first test run the Boneshaker went terribly awry, destroying several blocks of downtown Seattle and unearthing a subterranean vein of blight gas that turned anyone who breathed it into the living dead. Now it is sixteen years later, and a wall has been built to enclose the devastated and toxic city. Just beyond it lives Blue’s widow, Briar Wilkes. Life is hard with a ruined reputation and a teenaged boy to support, but she and Ezekiel are managing. Until Ezekiel undertakes a secret crusade to rewrite history. His quest will take him under the wall and into a city teeming with ravenous undead, air pirates, criminal overlords, and heavily armed refugees. And only Briar can bring him out alive.",
    genre: "Science Fiction",
    totalPage: 416,
    readPage: 250,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1433161048l/1137215._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "A Forgery of Roses",
    author: "Jessica S. Olson",
    description: "Myra Whitlock has a gift. One many would kill for. She’s an artist whose portraits alter people’s real-life bodies, a talent she must hide from those who would kidnap, blackmail, and worse in order to control it. Guarding that secret is the only way to keep her younger sister safe now that their parents are gone. But one frigid night, the governor’s wife discovers the truth and threatens to expose Myra if she does not complete a special portrait that would resurrect the governor's dead son. Desperate, Myra ventures to his legendary stone mansion. Once she arrives, however, it becomes clear the boy’s death was no accident. Someone dangerous lurks within these glittering halls. Someone harboring a disturbing obsession with portrait magic. Myra cannot do the painting until she knows what really happened, so she turns to the governor’s older son, a captivating redheaded poet. Together, they delve into the family’s most shadowed affairs, racing to uncover the truth before the secret Myra spent her life concealing makes her the killer’s next victim.",
    genre: "Fantasy, Religion, YA",
    totalPage: 368,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1624639782l/51941042.jpg",
    user_id: 1,  
    },
    {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story is of the fabulously wealthy Jay Gatsby and his new love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted gin was the national drink and sex the national obsession, it is an exquisitely crafted tale of America in the 1920s. The Great Gatsby is one of the great classics of twentieth-century literature.",
    genre: "Classics, Fiction, Academic, School, Historical",
    totalPage: 200,
    readPage: 200,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1490528560l/4671._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "Farenheight 451",
    author: "Ray Bradbury",
    description: 'Sixty years after its original publication, Ray Bradbury’s internationally acclaimed novel Fahrenheit 451 stands as a classic of world literature set in a bleak, dystopian future. Today its message has grown more relevant than ever before. Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known. ',
    genre: "Classics, Fiction, Literature, Fantasy",
    totalPage: 194,
    readPage: 25,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1383718290l/13079982.jpg",
    user_id: 1,  
    },
    {
    title: "Romeo and Juliet",
    author: "William Shakespeare",
    description: " In Romeo and Juliet, Shakespeare creates a violent world, in which two young people fall in love. It is not simply that their families disapprove; the Montagues and the Capulets are engaged in a blood feud. In this death-filled setting, the movement from love at first sight to the lovers’ final union in death seems almost inevitable. And yet, this play set in an extraordinary world has become the quintessential story of young love. In part because of its exquisite language, it is easy to respond as if it were about all young lovers. ",
    genre: " Classics, Plays. Fiction, Romance",
    totalPage: 821,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629680008l/18135._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "Catcher in the Rye",
    author: "J.D. Salinger",
    description: " It's Christmas time and Holden Caulfield has just been expelled from yet another school. Fleeing the crooks at Pencey Prep, he pinballs around New York City seeking solace in fleeting encounters - shooting the bull with strangers in dive hotels, wandering alone round Central Park, getting beaten up by pimps and cut down by erstwhile girlfriends. The city is beautiful and terrible, in all its neon loneliness and seedy glamour, its mingled sense of possibility and emptiness. Holden passes through it like a ghost, thinking always of his kid sister Phoebe, the only person who really understands him, and his determination to escape the phonies and find a life of true meaning. The Catcher in the Rye is an all-time classic in coming-of-age literature- an elegy to teenage alienation, capturing the deeply human need for connection and the bewildering sense of loss as we leave childhood behind. J.D. Salinger's classic novel of teenage angst and rebellion was first published in 1951. The novel was included on Time's 2005 list of the 100 best English-language novels written since 1923. It was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century. It has been frequently challenged in the court for its liberal use of profanity and portrayal of sexuality and in the 1950's and 60's it was the novel that every teenage boy wants to read.",
    genre: "Classics, Fiction, YA, Literature",
    totalPage: 277,
    readPage: 15,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1398034300l/5107.jpg",
    user_id: 1,  
    },
    {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde, Jeffrey Eugenides",
    description: "Oscar Wilde’s only novel is the dreamlike story of a young man who sells his soul for eternal youth and beauty. In this celebrated work Wilde forged a devastating portrait of the effects of evil and debauchery on a young aesthete in late-19th-century England. Combining elements of the Gothic horror novel and decadent French fiction, the book centers on a striking premise: As Dorian Gray sinks into a life of crime and gross sensuality, his body retains perfect youth and vigor while his recently painted portrait grows day by day into a hideous record of evil, which he must keep hidden from the world. For over a century, this mesmerizing tale of horror and suspense has enjoyed wide popularity. It ranks as one of Wilde's most important creations and among the classic achievements of its kind. ",
    genre: "Horror, Crime, Fiction",
    totalPage: 272,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546103428l/5297.jpg",
    user_id: 1,  
    },
    {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. "To Kill A Mockingbird" became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.',
    genre: "Historial Fiction, Academic, YA, Classics, Novels",
    totalPage: 336,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg",
    user_id: 1,  
    },
    {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    description: " In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV. Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.",
    genre: "YA, Adventure, Romance, Fantasy, Fiction, Apocalyptic",
    totalPage: 374,
    readPage: 375,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975l/2767052.jpg",
    user_id: 1,  
    },
    {
    title: "The Lightning Thief",
    author: "Pick Piordan",
    description: "Percy Jackson is a good kid, but he can't seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse - Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy's mom finds out, she knows it's time that he knew the truth about where he came from, and that he go to the one place he'll be safe. She sends Percy to Camp Half Blood, a summer camp for demigods (on Long Island), where he learns that the father he never knew is Poseidon, God of the Sea. Soon a mystery unfolds and together with his friends—one a satyr and the other the demigod daughter of Athena - Percy sets out on a quest across the United States to reach the gates of the Underworld (located in a recording studio in Hollywood) and prevent a catastrophic war between the gods.",
    genre: "Fantasy, YA, Fiction, Adventure, Childrens",
    totalPage: 377,
    readPage: 377,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1400602609l/28187.jpg",
    user_id: 1,  
    },
    {
    title: "The Maze Runner",
    author: "James Dashner",
    description: "If you ain’t scared, you ain’t human. When Thomas wakes up in the lift, the only thing he can remember is his name. He’s surrounded by strangers—boys whose memories are also gone. Nice to meet ya, shank. Welcome to the Glade. Outside the towering stone walls that surround the Glade is a limitless, ever-changing maze. It’s the only way out—and no one’s ever made it through alive. Everything is going to change. Then a girl arrives. The first girl ever. And the message she delivers is terrifying. Remember. Survive. Run.",
    genre: "Young Adult, Science Fiction, Fiction, Dystopia, Adventure, Mystery",
    totalPage: 384,
    readPage: 322,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1375596592l/6186357.jpg",
    user_id: 1,  
    },
    {
    title: "The Death Cure ",
    author: "Eric Carrasco",
    description: "An all new, original Maze Runner story set directly before the upcoming third film, The Death Cure. They used to live and die by the Maze—a seemingly endless labyrinth of deathtraps that kept the Gladers prisoner and in fear. But the day Thomas arrived, he motivated them all to push back...and escape. But what they discovered was far worse than any maze—a world scorched by disease and controlled by the oppressive organization, Wicked. Thomas, Aided by a band of rebels, now readies to take the fight right to Wicked’s doorstep in the hope of finding a cure for the plague that’s ravaging mankind. This all-new, authorized graphic novel bridges the gap between the second and third installments  ",
    genre: "Young Adult, Science Fiction, Fiction, Dystopia, Adventure, Mystery",
    totalPage: 96,
    readPage: 25,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1508955737l/25987085._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "Catching Fire",
    author: "Suzanne Collins",
    description: "Against all odds, Katniss Everdeen has won the annual Hunger Games with fellow district tribute Peeta Mellark. But it was a victory won by defiance of the Capitol and their harsh rules. The Capitol is angry. The Capitol wants revenge. Suzanne Collins continues the amazing story of Katniss Everdeen in Catching Fire, the second novel of the phenomenal Hunger Games trilogy. Read Chapters one and two to find out what happens next.",
    genre: "YA, Adventure, Romance, Fantasy, Fiction, Apocalyptic",
    totalPage: 465,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1388367944l/20349441.jpg",
    user_id: 1,  
    },
    {
    title: "Atomic Habits",
    author: "James Clear",
    description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights. Clear is known for his ability to distill complex topics into simple behaviors that can be easily applied to daily life and work. Here, he draws on the most proven ideas from biology, psychology, and neuroscience to create an easy-to-understand guide for making good habits inevitable and bad habits impossible. Along the way, readers will be inspired and entertained with true stories from Olympic gold medalists, award-winning artists, business leaders, life-saving physicians, and star comedians who have used the science of small habits to master their craft and vault to the top of their field. ",
    genre: "Nonfiction, Self-Help, Psychology, Productivity",
    totalPage: 319,
    readPage: 0,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1535115320l/40121378._SY475_.jpg",
    user_id: 1,  
    },
    {
    title: "The subtle art of not giving a F*uck",
    author: "Mark Manson",
    description: 'In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be "positive" all the time so that we can truly become better, happier people. For decades, we’ve been told that positive thinking is the key to a happy, rich life. "F**k positivity," Mark Manson says. "Let’s be honest, shit is f**ked and we have to live with it." In his wildly popular Internet blog, Manson doesn’t sugarcoat or equivocate. He tells it like it is—a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F**k is his antidote to the coddling, let’s-all-feel-good mindset that has infected American society and spoiled a generation, rewarding them with gold medals just for showing up. Manson makes the argument, backed both by academic research and well-timed poop jokes, that improving our lives hinges not on our ability to turn lemons into lemonade, but on learning to stomach lemons better. Human beings are flawed and limited—"not everybody can be extraordinary, there are winners and losers in society, and some of it is not fair or your fault." Manson advises us to get to know our limitations and accept them. Once we embrace our fears, faults, and uncertainties, once we stop running and avoiding and start confronting painful truths, we can begin to find the courage, perseverance, honesty, responsibility, curiosity, and forgiveness we seek. There are only so many things we can give a f**k about so we need to figure out which ones really matter, Manson makes clear. While money is nice, caring about what you do with your life is better, because true wealth is about experience. A much-needed grab-you-by-the-shoulders-and-look-you-in-the-eye moment of real-talk, filled with entertaining stories and profane, ruthless humor, The Subtle Art of Not Giving a F**k is a refreshing slap for a generation to help them lead contented, grounded lives.',
    genre: "Nonfiction, Self-Help, Psychology, Productivity",
    totalPage: 212,
    readPage: 106,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1465761302l/28257707.jpg",
    user_id: 1,  
    },
    {
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago, who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried near the Pyramids. Along the way he meets a Romany woman, a man who calls himself a king, and an alchemist, all of whom point Santiago in the right direction for his quest. No one knows what the treasure is, or whether Santiago will be able to surmount the obstacles in his path; but what starts out as a journey to find worldly goods turns into a discovery of treasure within. Lush, evocative, and deeply humane, the story of Santiago is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
    genre: "Classics, Fiction, Fantasy, Philosophy, Novels, Spirituality",
    totalPage: 182,
    readPage: 25,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1466865542l/18144590._SY475_.jpg",
    user_id: 1,  
    },
    
])